{
  "$schema": "./node_modules/wrangler/config-schema.json",
  "name": "niftypulse1",
  "pages_build_output_dir": ".next",
  "compatibility_date": "2024-01-01",
  "compatibility_flags": ["nodejs_compat"]
}

